[package]
name = "snarkOS"
version = "2.0.0"
edition = "2018"

[dependencies]
snarkvm = { path = "../snarkVM" }

[dependencies.anyhow]
version = "1"

[dependencies.bincode]
version = "1.0"
optional = true

[dependencies.chrono]
version = "0.4"

[dependencies.rocksdb]
version = "0.11"
optional = true

[dependencies.serde]
version = "1"

[dependencies.serde_json]
version = "1"

[features]
default = ["rocks"]
rocks = ["bincode", "rocksdb"]
noconfig = []
