[package]
name = "snarkos"
version = "2.0.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
    "aleo",
    "cryptography",
    "blockchain",
    "decentralized",
    "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "GPL-3.0"
edition = "2018"

[workspace]
members = ["ledger"]

[dependencies]
snarkvm = { path = "../snarkVM", features = ["parameters"] }
futures = { version = "0.3.0", features = ["thread-pool"]}
bytes = "1.0.0"

[dependencies.snarkos-ledger]
path = "./ledger"
version = "2.0.0"

[dependencies.anyhow]
version = "1"

[dependencies.bincode]
version = "1.0"

[dependencies.chrono]
version = "0.4"

[dependencies.circular-queue]
version = "0.2"

[dependencies.mpmc-map]
version = "0.2"

[dependencies.once_cell]
version = "1"

[dependencies.rand]
version = "0.8"

[dependencies.serde]
version = "1"

#[dependencies.serde_json]
#version = "1"

[dependencies.snow]
version = "0.8"
default-features = false
features = [
    "libsodium-resolver",
    "chacha20poly1305",
    "blake2",
    "sha2",
    "x25519-dalek",
    "rand"
]

[dependencies.tokio]
version = "1"
features = [
    "io-util",
    "parking_lot",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time"
]

[dependencies.tokio-util]
version = "=0.6.3"
features = ["full"]

[dependencies.tokio-stream]
version = "=0.1"

[dependencies.tracing]
version = "0.1"
default-features = false
features = [ "log" ]

[dependencies.tracing-subscriber]
version = "0.2"

[dependencies.twox-hash]
version = "1.6"

