[package]
name = "snarkOS"
version = "2.0.0"
edition = "2018"

[dependencies]
snarkvm = { path = "../snarkVM" }

[dependencies.anyhow]
version = "1"

[dependencies.bincode]
version = "1.0"

[dependencies.chrono]
version = "0.4"

[dependencies.rocksdb]
version = "0.11"

[dependencies.serde]
version = "1"

[dependencies.serde_json]
version = "1"
